In [1]:
import numpy as np
import nilearn
import pandas as pd
import os
import pycaret
from nilearn.connectome import sym_matrix_to_vec
import pickle

import json
from modeling_utils import *
from pycaret.classification import *

# Prepare Data for Pycaret

In [2]:
pca_features = np.load("group_pca_features.npy")

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
z_pca_features = scaler.fit_transform(pca_features)

In [3]:
print(pca_features.shape)

(936, 936)


In [7]:
data_paths = json.load(open('data_paths.json', 'r'))

In [8]:
participants = pd.read_csv("participants.csv")

In [9]:
pca_features = pd.DataFrame(pca_features)


In [10]:
z_pca_features = pd.DataFrame(z_pca_features)

In [11]:
pca_features["diagnosis"] = participants["diagnosis"].values

In [13]:
z_pca_features["diagnosis"] = participants["diagnosis"].values

In [14]:
z_pca_features

0         1         2         3         4         5         6  \
0   -0.037451  0.877742  0.851664  1.112781 -0.018495  1.495365 -0.928388   
1   -0.788723 -0.451073  1.064654 -1.862337  1.165596 -0.573462  0.844521   
2   -0.881122 -0.537879 -0.295877  0.944804 -0.444080 -1.085741  0.022726   
3   -0.037001 -0.744177 -0.141481 -0.251439  0.515631 -1.574424 -0.851996   
4    0.091975 -1.233866 -0.599923  1.511242 -2.006953 -1.232552  0.415964   
..        ...       ...       ...       ...       ...       ...       ...   
931  0.363801 -1.202154 -0.094210 -1.330508  0.219739  0.003685  1.497834   
932  0.408510 -0.459289 -1.362092  0.554097  0.312255  0.102078  2.286778   
933  0.335936 -0.455098 -1.772064  0.311882 -1.042444  0.307232  1.922203   
934 -0.235598 -0.984890 -0.643051  0.084609 -0.373247 -0.092442 -0.251151   
935 -0.025894 -0.902160 -0.204080 -1.407688 -0.433162 -0.215040  0.919751   

            7         8         9  ...       927       928       929  \
0    0.402388  0.998005 -3.025522  ...  1.795801  1.077133  0.709689   
1   -0.820587  1.161539 -2.357456  ...  0.619354 -0.213989 -1.205781   
2    0.769365  0.046054 -1.314172  ...  0.992217  0.232463 -0.471629   
3   -0.685689  0.158716 -0.547914  ... -0.885186  2.270919 -0.253184   
4   -0.587609  0.710219 -0.831671  ... -1.191025 -1.778869 -1.238162   
..        ...       ...       ...  ...       ...       ...       ...   
931 -0.500771  1.097432 -0.475188  ... -1.459166 -0.828485 -1.878068   
932 -1.079378 -1.124109 -0.955629  ...  0.815948 -0.619265  0.553024   
933  0.010731 -0.138276 -1.483103  ... -0.555294  2.339454  1.459950   
934 -0.031585 -0.479438 -1.116687  ... -1.393623 -0.063707 -0.323181   
935 -0.609091  1.192635 -0.172831  ... -1.514092  0.770050  1.196304   

          930       931       932       933       934       935  diagnosis  
0   -0.783696  0.394100  1.399889 -0.640550 -0.935044 -0.540477          1  
1    0.544656 -1.019299 -0.702494  0.892512  0.821963 -1.836511          1  
2   -0.604260 -1.051697  0.155915 -1.153250  0.716743 -0.020210          1  
3   -0.082594  0.340459  1.015177 -1.626901 -0.556460 -0.487620          1  
4    1.419053  1.477573  0.484267 -0.977878  0.321335 -2.106146          1  
..        ...       ...       ...       ...       ...       ...        ...  
931 -1.019063 -1.968675 -1.196955 -0.856778  0.489474 -1.582312          1  
932 -0.443896 -0.939387 -0.619790  0.370538 -0.588213  0.146271          1  
933  1.965130  0.802706  1.123248  2.534214 -1.481015  1.589744          1  
934 -0.040437 -0.267129  0.798329  0.434839 -0.557839 -0.863458          1  
935 -0.262891  0.838809  1.135158 -0.227232 -0.023282  2.596974          1  

[936 rows x 937 columns]

# Model Selection

In [21]:
exp = setup(z_pca_features, target = 'diagnosis', session_id = 123)

In [18]:
performance = compare_models()

\
                                                 
Initiated  . . . . . . . . . . . . . . . . . .   
Status     . . . . . . . . . . . . . . . . . .   
Estimator  . . . . . . . . . . . . . . . . . .   

                                            
                                            
Initiated                         14:52:47  
Status                    Fitting 10 Folds  
Estimator  Light Gradient Boosting Machine

KeyboardInterrupt: 

In [12]:
performance =pull()
performance.to_csv("results/pca_model_results.csv")


# Feature Selection

In [23]:
lr = create_model('lr')

In [24]:
feature_importance = pd.DataFrame({'Feature': np.array(get_config('X_test').columns).astype(int), 'Importance': abs(lr.coef_[0])})


In [ ]:
feature_importance

In [25]:
feature_importance["Importance"].min()
    

9.221089726456163e-05

In [27]:
 feature_importance["Importance"].max()


0.7711673765109432

In [158]:
np.save('results/component_importance.npy', feature_importance["Importance"].values)

SyntaxError: EOL while scanning string literal (3861651521.py, line 1)

In [28]:
eigenvectors = abs(np.load("group_pca_eigenvectors.npy"))

In [29]:
feat_importance_mat = feature_importance["Importance"].values * eigenvectors.T

In [31]:
feat_importance_mat.shape

(1700500, 936)

In [32]:
np.save('results/z_feature_importance_matrix.npy', feat_importance_mat)

In [61]:
all_features = np.load('all_features.npy')
feature_labels = np.load('feature_labels.npy')

In [62]:
scaler = StandardScaler()
z_all_features = scaler.fit_transform(all_features)
np.save('z_all_features.npy', z_all_features)

In [64]:
z_all_features = pd.DataFrame(z_all_features)

In [37]:
feat_importance_mat = np.load('results/feature_importance_matrix.npy')
z_feat_importance_mat = np.load('results/z_feature_importance_matrix.npy')

In [44]:
best_features = get_n_best_features(feat_importance_mat, 1000, all_features, feature_labels)

In [43]:
feat_importance_mat

array([[1.32625084e-05, 3.12879371e-05, 4.66042814e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.15473699e-05, 3.24204194e-05, 3.72083719e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.50533326e-05, 1.71357340e-05, 9.86628015e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.10818214e-07, 8.54103142e-06, 1.89452656e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.92798257e-06, 1.21348639e-05, 3.13698906e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        9.12861588e-06, 2.94646982e-05, 8.79953359e-06]])

In [42]:
z_feat_importance_mat

array([[3.05214219e-04, 2.13681379e-04, 5.35857306e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.65743205e-04, 2.21415681e-04, 4.27822881e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.46427012e-04, 1.17028721e-04, 1.13442760e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.14210816e-06, 1.85266425e-05, 3.33923275e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.05048995e-05, 2.63221471e-05, 5.52915796e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.39130703e-04, 6.39128814e-05, 1.55097803e-04]])

In [65]:
z_best_features = get_n_best_features(z_feat_importance_mat, 1000, z_all_features, feature_labels)

In [52]:
best_features.values == z_best_features.values

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])

In [53]:
z_best_features.values

array([[-2.76871544, -3.09602424, -3.38060971, ...,  2.70305203,
         1.07287186,  0.84343466],
       [-0.83250696, -1.13576647, -1.29630891, ...,  2.77670981,
         0.55735037,  0.3127236 ],
       [ 0.14768757,  0.39807936,  0.62503312, ..., -0.55777919,
         0.71616216,  0.7690363 ],
       ...,
       [-2.01000404, -1.8392076 , -2.42936382, ...,  0.44546627,
         0.75621637,  1.27259654],
       [-0.95856868, -0.65262072, -1.53780944, ...,  0.77340449,
         0.75496435,  0.45636082],
       [-1.88806156, -1.10484479, -1.18756825, ...,  0.86996625,
         0.17837424,  0.936723  ]])

In [66]:
z_best_features

grad_comb_200_aligned_128605  grad_comb_200_aligned_131005  \
0                       -0.979312                     -1.229149   
1                        0.882320                      0.668892   
2                        1.824761                      2.154055   
3                        1.224722                     -0.826956   
4                        1.517285                      1.429864   
..                            ...                           ...   
931                     -0.603891                     -0.245231   
932                      0.769465                      0.541335   
933                     -0.249823                     -0.012223   
934                      0.761114                      1.136703   
935                     -0.132578                      0.698832   

     grad_comb_200_aligned_132005  grad_comb_200_aligned_124404  \
0                       -1.693440                     -0.743390   
1                        0.400625                      0.107486   
2                        2.330968                     -0.045081   
3                        0.833915                      0.896095   
4                        0.328429                      0.758120   
..                            ...                           ...   
931                     -0.388363                     -0.086755   
932                      0.330729                     -0.150355   
933                     -0.737738                     -0.358735   
934                      0.157993                      0.273817   
935                      0.509875                      0.048041   

     grad_comb_200_aligned_24805  grad_comb_200_aligned_129605  \
0                      -1.449312                     -1.553495   
1                       0.531337                     -0.360902   
2                       1.176161                      1.296632   
3                       1.065759                      0.173308   
4                       0.566685                      1.185162   
..                           ...                           ...   
931                    -0.238417                      0.332270   
932                    -0.125328                      1.536802   
933                     0.242306                     -0.136107   
934                    -0.297826                      0.218955   
935                     0.339527                     -0.104733   

     grad_comb_200_aligned_130605  grad_comb_200_aligned_131400  \
0                       -0.836661                      0.865901   
1                        0.452792                     -1.069062   
2                        1.542939                     -2.382151   
3                        0.992966                     -0.917469   
4                       -0.078070                      2.145492   
..                            ...                           ...   
931                     -0.364208                     -1.400307   
932                      0.551731                     -0.282834   
933                     -0.046918                      3.005059   
934                      0.414988                     -0.419708   
935                      0.555711                     -0.359113   

     grad_comb_200_aligned_29600  grad_comb_200_aligned_133000  \
0                       0.380010                      0.720190   
1                      -0.636775                      0.014585   
2                      -1.316156                     -1.211539   
3                      -1.534588                     -0.951506   
4                      -0.260183                     -0.914492   
..                           ...                           ...   
931                    -0.490671                      0.216827   
932                    -0.442942                     -0.699019   
933                     2.676788                      0.472529   
934                     0.350903                      0.049296   
935                    -0.189058                     -0.482348   

    

In [67]:
z_best_features["diagnosis"] = participants['diagnosis'].values

In [10]:
best_features = pd.read_csv("best_features/1000_best_features.csv")
best_features["diagnosis"] = participants["diagnosis"]

In [71]:
exp2 = setup(z_best_features, target = 'diagnosis', session_id = 123)


In [72]:
best_model = compare_models(n_select = 1)

In [43]:
exp3 = setup(grad1_features, target = 'diagnosis', session_id = 123)

In [ ]:
best_model = compare_models(n_select = 1)

In [16]:
performance = pull()
performance = performance[performance['Model'] != 'Dummy Classifier']
imp_features_mean_acc = performance['Accuracy'].mean()
imp_features_mean_auc = performance.loc[performance['AUC'] != 0, 'AUC'].mean()

In [17]:
performance[performance["Model"] != "Dummy Classifier"]

Model  Accuracy     AUC  Recall   Prec.  \
et                 Extra Trees Classifier    0.7341  0.7821  0.4432  0.8021   
rf               Random Forest Classifier    0.7083  0.7457  0.4258  0.6857   
gbc          Gradient Boosting Classifier    0.7082  0.7331  0.4765  0.6863   
xgboost         Extreme Gradient Boosting    0.6857  0.7298  0.4871  0.6361   
lightgbm  Light Gradient Boosting Machine    0.6758  0.7315  0.4932  0.6044   
knn                K Neighbors Classifier    0.6662  0.6867  0.4091  0.5730   
ada                  Ada Boost Classifier    0.6595  0.6898  0.5697  0.5816   
nb                            Naive Bayes    0.6406  0.7122  0.6530  0.5274   
lr                    Logistic Regression    0.6339  0.6591  0.5121  0.5430   
svm                   SVM - Linear Kernel    0.6276  0.0000  0.4879  0.5041   
ridge                    Ridge Classifier    0.6047  0.0000  0.5212  0.4936   
lda          Linear Discriminant Analysis    0.6047  0.6698  0.5212  0.4936   
dt               Decision Tree Classifier    0.5923  0.5717  0.4803  0.4755   
qda       Quadratic Discriminant Analysis    0.3851  0.5000  1.0000  0.3851   

              F1   Kappa     MCC  TT (Sec)  
et        0.5503  0.3872  0.4331     0.870  
rf        0.5156  0.3298  0.3513     0.459  
gbc       0.5548  0.3484  0.3667     0.454  
xgboost   0.5360  0.3094  0.3242     0.735  
lightgbm  0.5272  0.2896  0.3025     0.657  
knn       0.4687  0.2440  0.2519     0.453  
ada       0.5651  0.2886  0.2956     0.443  
nb        0.5771  0.2713  0.2834     0.659  
lr        0.5191  0.2266  0.2309     0.484  
svm       0.4920  0.2026  0.2017     0.418  
ridge     0.4968  0.1767  0.1818     0.431  
lda       0.4968  0.1767  0.1818     0.470  
dt        0.4745  0.1434  0.1447     0.467  
qda       0.5560  0.0000  0.0000     0.432

In [18]:
imp_features_mean_auc

0.6701153846153847

In [19]:
p_mean_acc, p_mean_auc = random_feature_test(5, all_features, imp_features_mean_acc, imp_features_mean_auc, participants, n_tests = 5, workers = -1) # parallelize it

Fitting models on randomly picked features...
Test 1...
Test 2...
Test 3...
Test 4...
Test 5...


In [97]:
max_indices = np.argsort(-abs(eigenvectors[624]))[:500]

In [98]:
best_features = all_features.iloc[:, max_indices]
best_features["diagnosis"] = participants['diagnosis'].values


In [99]:
best_features

1699658    1700181    1698658    1693658    1688658    1683658  \
0     5.536804   5.878878   5.344567   5.334474   5.328539   5.317946   
1    14.333108   9.979888  14.230288  14.206952  14.205391  14.160662   
2     4.157663   3.402193   4.040522   4.037799   4.032608   4.027895   
3     5.470017   4.096760   5.344577   5.339439   5.337820   5.335412   
4     4.842222   4.437483   4.687413   4.680842   4.678665   4.669846   
..         ...        ...        ...        ...        ...        ...   
931  14.842199   4.339172  14.744095  14.701351  14.700188  14.680717   
932   6.525610  12.711563   6.311018   6.299792   6.291920   6.285650   
933  13.605404   5.375874  13.348641  13.333973  13.330600  13.306946   
934   4.402195   4.063575   4.216046   4.213300   4.210207   4.197258   
935   4.594504   3.763266   4.502938   4.500320   4.496573   4.492919   

       1678658    1673658    1668658    1663658    1658658    1700306  \
0     5.313520   5.310560   5.304131   5.295803   5.289344   5.398040   
1    14.157491  14.156571  14.094849  14.037749  14.011536   5.273987   
2     4.024142   4.020759   4.003807   3.998255   3.995682   5.054697   
3     5.328280   5.321155   5.272483   5.269787   5.266957   5.462944   
4     4.667477   4.663828   4.656624   4.650346   4.642360   5.994661   
..         ...        ...        ...        ...        ...        ...   
931  14.678709  14.671810  14.597150  14.572822  14.553917   5.605468   
932   6.283470   6.277626   6.268454   6.265530   6.263588  14.507781   
933  13.288588  13.278637  13.168717  13.117378  13.111587   5.952071   
934   4.193523   4.189017   4.174906   4.169051   4.164424   4.799710   
935   4.490192   4.486748   4.483632   4.480388   4.447798   4.655886   

       1653658    1648658    1643658    1638658    1633658    1628658  \
0     5.285972   5.281322   5.278821   5.274798   5.272658   5.269823   
1    13.910665  13.904008  13.874302  13.778037  13.754248  13.747129   
2     3.992677   3.987551   3.982945   3.973833   3.970959   3.960366   
3     5.252597   5.245981   5.237215   5.216593   5.213827   5.209349   
4     4.635133   4.623836   4.621067   4.617218   4.609961   4.606414   
..         ...        ...        ...        ...        ...        ...   
931  14.429550  14.425319  14.387151  14.267906  14.244669  14.221321   
932   6.259102   6.256122   6.253562   6.248139   6.246393   6.241560   
933  13.046508  13.036985  13.007396  12.933359  12.911913  12.888426   
934   4.161377   4.157306   4.155297   4.137494   4.135812   4.133195   
935   4.443390   4.441261   4.438308   4.426509   4.423558   4.414216   

       1623658    1618658    1613658    1699181    1694181    1689181  \
0     5.257806   5.255117   5.249315   5.698673   5.675772   5.670747   
1    13.740100  13.737748  13.689903   9.890387   9.877807   9.835943   
2     3.957990   3.955742   3.949609   3.276571   3.270881   3.267066   
3     5.204112   5.201791   5.195356   3.998866   3.992947   3.985997   
4     4.602195   4.598043   4.578986   4.314583   4.310990   4.307313   
..         ...        ...        ...        ...        ...        ...   
931  14.208774  14.207839  14.162506   4.215724   4.209879   4.206460   
932   6.238581   6.234316   6.220693  12.538233  12.526902  12.490067   
933  12.885155  12.884071  12.816207   4.983872   4.977409   4.972950   
934   4.129742   4.123951   4.117990   3.921825   3.917113   3.912397   
935   4.410227   4.405395   4.402681   3.665994   3.663483   3.659932   

       1608658    1684181    1603658    1679181    1674181    1669181  \
0     5.214864   5.667524   5.212657   5.662399   5.651461   5.645355   
1    13.582278   9.834071  13.581114   9.783668   9.756761   9.754732   
2     3.946479   3.263356   3.942608   3.260808   3.255913   3.253053   
3     5.177601   3.982371   5.171702   3.976822   3.970370   3.967996   
4     4.569021   4.299555   4.563917   4.283759   4.279780   4.277314   
..         ...        ...        ...        ...        ...   

In [100]:
exp3 = setup(best_features, target = 'diagnosis', session_id = 123)
